# Generated by Django 5.1.3 on 2024-11-06 17:24

from django.db import migrations, models
from datetime import datetime, timedelta
import random

def create_initial_tasks(apps, schema_editor):
    Task = apps.get_model('Tasks', 'Task')
    
    statuses = ["Pending", "Completed"]
    tasks = [
        {
            "title": f"Task {i + 1}",
            "description": f"This is the description for task {i + 1}",
            "due_date": datetime.now().date() + timedelta(days=random.randint(1, 50)),
            "status": random.choice(statuses),
        }
        for i in range(50) 
    ]
    
    for task_data in tasks:
        Task.objects.create(**task_data)

def delete_initial_tasks(apps, schema_editor):
    Task = apps.get_model('your_app_name', 'Task')
    Task.objects.filter(title__regex=r"^Task [1-9]$|^Task [12][0-9]$|^Task 50$").delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)),
            ],
        ),
        migrations.RunPython(create_initial_tasks, reverse_code=delete_initial_tasks),

    ]
